tasks:
  - type: docker-build
    image: docker-deployer
    context: images/docker-deployer
    file: images/docker-deployer/Dockerfile
    custom_tags:
      - 2.3.0
    registries:
      - gitlab

  - type: docker-build
    image: hephaestus
    context: images/hephaestus
    file: images/hephaestus/Dockerfile
    custom_tags:
      - 1.1.0
    registries:
      - gitlab

