tasks:
  - type: docker-build
    image: docker-deployer
    context: images/docker-deployer
    file: images/docker-deployer/Dockerfile
    custom_tags:
      - 2.5.0
    registries:
      - gitlab

